### PR TITLE
[Chore]: Fix issues raised by flake8 and black

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixes issues raised by flake8 (unused imports) and black code linting errors.
These errors were persisting for quite some time, so I though I would just
fix them :)

Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>

### CODE REVIEW

**Comment by r0rshark** [comment]
Thanks, looks like black need another minor fix

**Comment by abishekvashok** [comment]
@r0rshark done :)

**Comment by r0rshark** [comment]
@abishekvashok  besides the fix can we also exclude the pyi files from the checking similarly to what we did in pyre-check. It looks like our internal CI is not caring about those (we can keep the fix though).

**Comment by abishekvashok** [comment]
Not sure if it's the way we did in pyre-check, but this should do it :)

**Pull request closed without merging**
