### PR TITLE
Fix broken pyre github action

### PR DESCRIPTION
**Pull request by abishekvashok**
Fix broken pyre github action by adding pyre-fixme comments.

Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>

### CODE REVIEW

**Comment by abishekvashok** [comment]
I saw the pyre checks failing and thought it would be nice to fix 'em.

A word of caution: I am highly doubtful of this approach, as in fact,
we are indeed returning a generator over an iterator. However, if
you guys prefer to keep it this way, I am absolutely fine :)

Pyre action was broken in https://github.com/facebook/sapp/commit/ca340dfe7c562cc8c53f8bc80a8bca7cd43da1f1
But from the commit message, I sense this is something internal -
maybe there's an internal reason why the fixme comments were
removed. In that case, feel free to close this PR :) This is just my
desire to keep all the tests passing.

**Comment by 0xedward** [comment]
Hey @abishekvashok! Thanks for being proactive here :)

It turns out this issue is caused by our nightly version being out of sync with our internal version. The team is working on deleting older versions of `pyre-check-nightly` so we can free up some storage space for newer versions. I'll get back to you with updates as soon as I heard about them

**Comment by 0xedward** [comment]
Closing this PR, because we fixed the pyre-check nightly issue and recent [Pyre workflows have been passing](https://github.com/facebook/sapp/actions/workflows/pyre.yml)

Thanks again @abishekvashok for your work here!

**Comment by abishekvashok** [comment]
Always a pleasure working with you guys :)

**Pull request closed without merging**
