### PR TITLE
Update vulnerable dependency in SAPP

### PR DESCRIPTION
**Pull request by abishekvashok**
Updates react-dev-utils to version 11.0.4 thereby mitigating 2 high
severity and 5 moderate severity vulnerabilities. Regenerates
package-lock.json as well.

The changes have been tested, and verified that this doesn't break
any functionality and/or feature in the web app. 

Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>
Fixes: https://github.com/MLH-Fellowship/pyre-check/issues/44

### CODE REVIEW

**Comment by abishekvashok** [comment]
I was able to resolve 7 out of 14 vulnerabilities here, the rest 7 are either from the latest version of react-dev-utils or web pack. We can update them when the updates are available :)

**Comment by 0xedward** [comment]
Although we didn't spend too much time looking into it, we previously tried updating some packages, including `react-dev-utils`, without much success (See https://github.com/facebook/sapp/commit/11de043927cea6bba22dc0a69c476c1c9414b76d commit description).

>The changes have been tested, and verified that this doesn't break any functionality and/or feature in the web app.

@abishekvashok Could you include a test plan with reproduction steps for some of the things you tested?

**Comment by abishekvashok** [comment]
> @abishekvashok Could you include a test plan with reproduction steps for some of the things you tested?

Not much, I just checked if the ui worked, inspected the console and made sure the errors/warnings thrown there were already present before the change.

**Comment by abishekvashok** [comment]
@0xedward that commit description is scary 😦 I don't want to wander to make that much of work for anyone. Sorry you had to go through that, yeah, this is not a breaking change as `npm audit fix --force` only makes breaking changes and not `npm audit fix`. Although, I tested building and running the app, I don't want to be that guy breaking changes -- and if this vulnerability is something we could ignore, I am totally fine to close this pull request.

**Pull request closed without merging**
